controller:
  image:
    repository: quay.io/metallb/controller
    # renovate: datasource=docker depName=quay.io/metallb/controller
    tag: "v0.14.9"
speaker:
  image:
    repository: quay.io/metallb/speaker
    # renovate: datasource=docker depName=quay.io/metallb/speaker
    tag: "v0.14.9"
frr:
  image:
    repository: quay.io/frrouting/frr
    # renovate: datasource=docker depName=quay.io/frrouting/frr
    tag: "9.1.3"